spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://localhost:4200"]
            allowedMethods: [GET,POST,PUT,DELETE,OPTIONS]
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true

      routes:
        # User Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        # Product Service
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

        # Order Service - separate routes for /cart and /order
        - id: order-service-cart
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/cart/**

        - id: order-service-order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
